# Make sure to set environment variable OPENAI_API_KEY
from openai import OpenAI
import json
import httpx
import os
import click

weatherapikey = "None"
weatherapikeyfile = "/Users/satishkumar/.hc/weatherapi.key"
with open(weatherapikeyfile, "r") as apikey:
    weatherapikey = apikey.read()
    weatherapikey = weatherapikey.replace("\n", "")

openai_api_key = os.getenv("OPENAI_API_KEY")
if not openai_api_key:
    with open("/Users/satishkumar/.hc/openai.key", "r") as apikey:
        openai_api_key = apikey.read()
        openai_api_key = openai_api_key.replace("\n", "")


print(f"OpenAI API key is {openai_api_key}... {len(openai_api_key)} characters long")
client = OpenAI(api_key=openai_api_key)

# 1. Define a list of callable tools for the model
tools = [
    {
        "type": "function",
        "name": "get_weather",
        "description": "Retrieves current weather for the given location.",
        "parameters": {
            "type": "object",
            "properties": {
              "location": {
                "type": "string",
                "description": "City and country e.g. Bogotá, Colombia"
              },
              "units": {
                "type": "string",
                "enum": ["celsius", "fahrenheit"],
                "description": "Units the temperature will be returned in."
              }
          }
        }
    }
]

def get_weather(location, units="celsius"):
    with httpx.Client() as client:
        response = client.get(f"https://api.weatherapi.com/v1/current.json?key={weatherapikey}&q={location}&aqi=no")
        data = response.json()
        print(f"Weather data of {location} is {json.dumps(data)}")
        return json.dumps(data)


def simple_agent(user_message):
    print(f"Invoking the model with user message {user_message}")

    # Create a running input list we will add to over time
    input_list = [
        {"role": "user", "content": user_message}
    ]

    # 2. Prompt the model with tools defined
    response = client.responses.create(
        model="gpt-5.4-mini",
        tools=tools,
        input=input_list,
    )
    print(f"Response is {response.model_dump_json(indent=2)}")
    # Save function call outputs for subsequent requests
    input_list += response.output

    for item in response.output:
        if item.type == "function_call":
            print("Function call is invoked")
            if item.name == "get_weather":
                print("OpenAI wants to invoke get_weather function")
                print(f"Arguments are {json.loads(item.arguments)}")
                # 3. Execute the function logic for get_weather
                weather_data = get_weather(json.loads(item.arguments))
                print(f"Weather data is {weather_data}")
                # 4. Provide function call results to the model
                input_list.append({
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": weather_data
                    })

    print("Final input:")
    print(input_list)

    print("Invoking the model with get_weather output")
    response = client.responses.create(
        model="gpt-5",
        instructions="Respond only with a response generated by a tool.",
        tools=tools,
        input=input_list,
    )

    # 5. The model should be able to give a response!
    print("Final output:")
    print(response.model_dump_json(indent=2))
    print("\n" + response.output_text)

@click.command()
@click.argument("user_input")
def main(user_input):
    simple_agent(user_input)

if __name__ == "__main__":
    main()